# Generated by Django 2.2.5 on 2019-11-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0002_auto_20191125_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='District',
            field=models.CharField(choices=[('syllhet', 'Syllhet'), ('habiganj', 'Habiganj'), ('lalmonirhat', 'Lalmonirhat'), ('rajshahi', 'Rajshahi'), ('pabna', 'Pabna'), ('mymensingh', 'Mymensingh'), ('khulna', 'Khulna'), ('tangail', 'Tangail')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='blood_group',
            field=models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
