# Generated by Django 2.2.5 on 2019-12-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0003_auto_20191125_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='status',
            field=models.CharField(choices=[('available', 'AVAILABLE'), ('unavailable', 'UNAVAILABLE')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
