# Generated by Django 2.2.5 on 2019-12-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0004_userprofileinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='First_name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Last_name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
