# Generated by Django 2.2.5 on 2019-12-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0005_auto_20191216_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='District',
            field=models.CharField(choices=[('Syllhet', 'Syllhet'), ('Habiganj', 'Habiganj'), ('Lalmonirhat', 'Lalmonirhat'), ('Rajshahi', 'Rajshahi'), ('Pabna', 'Pabna'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Tangail', 'Tangail')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='status',
            field=models.CharField(choices=[('Available', 'AVAILABLE'), ('Unavailable', 'UNAVAILABLE')], max_length=10),
        ),
    ]
